Create zh_cn.json
AViewFromTheTop/SimpleCopperPipesMC pull request #11
Opened 2022-11-27 02:09 UTC by HaooooZhang

2022-11-28 08:46 UTC, yaodaosang commented on src/main/resources/assets/lunade/lang/zh_cn.json
> +  "block.lunade.glowing_gray_pipe": "发光的发光的灰色管道",
多了个“发光的”

2022-11-28 08:50 UTC, A-Black-Fish commented on src/main/resources/assets/lunade/lang/zh_cn.json
> +  "block.lunade.glowing_gray_pipe": "发光的发光的灰色管道",
需要修改

2022-11-28 08:59 UTC, yaodaosang commented
pipe在前后的翻译是否需要统一一下？
如：Copper Pipe 翻译为铜**管**，而 Glowing Purple Pipe 却翻译为发光的紫色**管道**。
可能统一为管道更好些？

2022-11-28 10:02 UTC, HaooooZhang commented on src/main/resources/assets/lunade/lang/zh_cn.json
> +  "block.lunade.glowing_gray_pipe": "发光的发光的灰色管道",
感谢

2022-11-29 00:34 UTC, A-Black-Fish requested changes

2022-11-29 00:34 UTC, A-Black-Fish commented on src/main/resources/assets/lunade/lang/zh_cn.json
> +  "block.lunade.corroded_pipe": "腐蚀的铜管",
```suggestion
  "block.lunade.copper_pipe": "铜管道",
  "block.lunade.exposed_copper_pipe": "斑驳的铜管道",
  "block.lunade.weathered_copper_pipe": "锈蚀的铜管道",
  "block.lunade.oxidized_copper_pipe": "氧化的铜管道",
  "block.lunade.waxed_copper_pipe": "涂蜡铜管道",
  "block.lunade.waxed_exposed_copper_pipe": "斑驳的涂蜡铜管道",
  "block.lunade.waxed_weathered_copper_pipe": "锈蚀的涂蜡铜管道",
  "block.lunade.waxed_oxidized_copper_pipe": "氧化的涂蜡铜管道",
  "block.lunade.corroded_pipe": "腐蚀的铜管道",
```

2022-11-29 00:34 UTC, A-Black-Fish commented on src/main/resources/assets/lunade/lang/zh_cn.json
> +  "stat.lunade.inspect_copper_pipe": "搜索铜管"
```suggestion
  "stat.lunade.inspect_copper_pipe": "铜管道使用次数"
```

2022-11-29 00:37 UTC, A-Black-Fish commented
o对了，glowing 在游戏里面是荧光的意思

2023-01-16 19:23 UTC, merged